// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6KfpyYEUlIl4VkpnKjCsYmEkXNr9phgY',
    appId: '1:82702087091:web:9d7cba2d66b09286c311c6',
    messagingSenderId: '82702087091',
    projectId: 'project1-dfa42',
    authDomain: 'project1-dfa42.firebaseapp.com',
    storageBucket: 'project1-dfa42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQZTUcINQl2Ozxs5IdN-epOhSW_WBLhPE',
    appId: '1:82702087091:android:a3d99de1f80f93f4c311c6',
    messagingSenderId: '82702087091',
    projectId: 'project1-dfa42',
    storageBucket: 'project1-dfa42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeiRGTHR-ZE_P9WDKWVzOJNegl0ihXGZA',
    appId: '1:82702087091:ios:71dd11ed4202bf61c311c6',
    messagingSenderId: '82702087091',
    projectId: 'project1-dfa42',
    storageBucket: 'project1-dfa42.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeiRGTHR-ZE_P9WDKWVzOJNegl0ihXGZA',
    appId: '1:82702087091:ios:71dd11ed4202bf61c311c6',
    messagingSenderId: '82702087091',
    projectId: 'project1-dfa42',
    storageBucket: 'project1-dfa42.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6KfpyYEUlIl4VkpnKjCsYmEkXNr9phgY',
    appId: '1:82702087091:web:a2529cf83832c3a5c311c6',
    messagingSenderId: '82702087091',
    projectId: 'project1-dfa42',
    authDomain: 'project1-dfa42.firebaseapp.com',
    storageBucket: 'project1-dfa42.appspot.com',
  );
}
